hostname: R2

interfaces:
  - name: Ethernet0/0
    ip_address: 12.1.1.2
    subnet_mask: 255.255.255.0
  
  - name: Ethernet0/1
    ip_address: 23.1.1.2
    subnet_mask: 255.255.255.0
  
  - name: Loopback0
    ip_address: 2.2.2.2
    subnet_mask: 255.255.255.255
  
  - name: Loopback100
    ip_address: 22.22.22.22
    subnet_mask: 255.255.255.255