- hostname: R1
  inventory_file: R1.yaml
  device_type: cisco_ios
  host: 12.1.1.1
  username: admin
  password: cisco123

- hostname: R2
  inventory_file: R2.yaml
  device_type: cisco_ios
  host: 12.1.1.2
  username: admin
  password: cisco123

- hostname: R3
  inventory_file: R3.yaml
  device_type: cisco_ios
  host: 23.1.1.3
  username: admin
  password: cisco123